# Generated by Django 5.1.5 on 2025-02-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desideorio',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
