# Generated by Django 5.1.5 on 2025-02-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_desideorio_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desideorio',
            name='comments_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desideorio',
            name='donat_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
